{% set name = "elyra-python-editor-extension" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-python-editor-extension-{{ version }}.tar.gz
  sha256: ae9055e035ea194a812ab3b00f7f1125fdf5278e40dd27b27469261d9003df93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elyra-server ==2.2.4
    - python >=3.6

test:
  commands:
    - exit 0

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra JupyterLab extension providing support for Python scripts. Learn more at https://elyra.readthedocs.io/en/stable/user_guide/enhanced-script-support.html
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
